# Generated by Django 5.2.1 on 2025-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="alerta",
            field=models.BooleanField(default=False),
        ),
    ]
