# Generated by Django 5.2.1 on 2025-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_thread_alerta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddField(
            model_name="thread",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
